In [1]:
import seaborn as sns
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neighbors import KNeighborsTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score 



In [44]:
titanic = sns.load_dataset("titanic")
titanic.head()
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [45]:
titanic = titanic.loc[:, ["survived", "pclass", "sex", "age", "sibsp", "parch", "fare"]]
titanic.dropna(subset=["age"], axis=0, inplace=True)

# 범주형 데이터 변환


In [46]:
X = titanic.loc[:, "pclass":"fare"]
y = titanic["survived"]



In [47]:
##DT, rf, gb survived = 1 alive
X = pd.get_dummies(X, columns = ["sex"], drop_first=True)
print(X.head())

   pclass   age  sibsp  parch     fare  sex_male
0       3  22.0      1      0   7.2500      True
1       1  38.0      1      0  71.2833     False
2       3  26.0      0      0   7.9250     False
3       1  35.0      1      0  53.1000     False
4       3  35.0      0      0   8.0500      True


In [39]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.model_selection import StratifiedKFold, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_validate, StratifiedKFold, GridSearchCV
from sklearn.tree import DecisionTreeClassifier

In [40]:
## dt
dt = DecisionTreeClassifier()
params = {
    "max_depth" : range(3, 20, 1),
    "max_leaf_nodes" : range(3, 20, 1) 
}
splitter = StratifiedKFold(n_splits = 5, shuffle = True)
gs_dt = GridSearchCV(dt, param_grid = params, cv = splitter)
gs_dt.fit(X,y)


c:\Users\KTJ\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\ma\core.py:2881: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,


GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=True),
             estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': range(3, 20),
                         'max_leaf_nodes': range(3, 20)})

In [41]:
print("best parameters = ",gs_dt.best_estimator_)
print("best cv score = {:.4f}".format( gs_dt.best_score_))

best parameters =  DecisionTreeClassifier(max_depth=15, max_leaf_nodes=16)
best cv score = 0.8338


In [43]:
## rf
rf = RandomForestClassifier()

params = {
    "max_depth" : range(3, 15, 1),
    "n_estimators" : range(90, 120, 1)
}
splitter = StratifiedKFold(n_splits=5, shuffle=True)
grid_rf = GridSearchCV(rf, param_grid=params, cv = splitter)
grid_rf.fit(X, y)

c:\Users\KTJ\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\ma\core.py:2881: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,


GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=True),
             estimator=RandomForestClassifier(),
             param_grid={'max_depth': range(3, 15),
                         'n_estimators': range(90, 120)})

In [48]:
print("best parameters = ",grid_rf.best_estimator_)
print("best cv score = {:.4f}".format( grid_rf.best_score_))

best parameters =  RandomForestClassifier(max_depth=8, n_estimators=112)
best cv score = 0.8373


In [54]:
gb = GradientBoostingClassifier()
params = {
    "max_depth" : range(3, 20, 1),
    "learning_rate": np.arange(0.1, 1.0, 0.1)
}
splitter = StratifiedKFold(n_splits=5, shuffle=True)
gs_gb = GridSearchCV(gb, param_grid=params, cv = splitter)
gs_gb.fit(X,y)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=True),
             estimator=GradientBoostingClassifier(),
             param_grid={'learning_rate': array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]),
                         'max_depth': range(3, 20)})

In [55]:
print("best parameters = ",gs_gb.best_estimator_)
print("best cv score = {:.4f}".format( gs_gb.best_score_))

best parameters =  GradientBoostingClassifier(learning_rate=np.float64(0.1), max_depth=4)
best cv score = 0.8179


In [58]:
wine = pd.read_csv("https://bit.ly/wine-date")
wine.head()

alcohol  sugar    pH  class
0      9.4    1.9  3.51    0.0
1      9.8    2.6  3.20    0.0
2      9.8    2.3  3.26    0.0
3      9.8    1.9  3.16    0.0
4      9.4    1.9  3.51    0.0

In [61]:
wine["class"] = wine["class"].astype("int32").astype('category')
wine.head()

alcohol  sugar    pH class
0      9.4    1.9  3.51     0
1      9.8    2.6  3.20     0
2      9.8    2.3  3.26     0
3      9.8    1.9  3.16     0
4      9.4    1.9  3.51     0

In [62]:
X = wine.iloc[:, :-1]
y = wine["class"]

In [67]:
standardscaler = StandardScaler()
X_scaled = standardscaler.fit_transform(X)
X_scaled[:10]


array([[-0.91546416, -0.7447781 ,  1.81308951],
       [-0.58006813, -0.59764007, -0.11507303],
       [-0.58006813, -0.66069923,  0.25811972],
       [-0.58006813, -0.7447781 , -0.3638682 ],
       [-0.91546416, -0.7447781 ,  1.81308951],
       [-0.91546416, -0.76579782,  1.81308951],
       [-0.91546416, -0.80783726,  0.50691489],
       [-0.41237012, -0.89191614,  1.06670401],
       [-0.83161516, -0.72375839,  0.88010764],
       [ 0.00687492,  0.13805008,  0.81790884]])

In [68]:
from sklearn.linear_model import LogisticRegression

In [69]:
lr = LogisticRegression(max_iter=100)
splitter = StratifiedKFold(n_splits=5, shuffle=True)
scores = cross_validate(lr, X_scaled, y, cv = splitter)

In [70]:
print(scores["test_score"])

[0.78923077 0.77692308 0.78367975 0.79214781 0.76366436]


In [71]:
lr.fit(X_scaled, y)

LogisticRegression()

In [73]:
lr.predict_proba(X_scaled[:10])

array([[0.77202535, 0.22797465],
       [0.3608078 , 0.6391922 ],
       [0.44961173, 0.55038827],
       [0.37654449, 0.62345551],
       [0.77202535, 0.22797465],
       [0.77810814, 0.22189186],
       [0.59800521, 0.40199479],
       [0.66068716, 0.33931284],
       [0.61725242, 0.38274758],
       [0.19105714, 0.80894286]])